<<<<<<< HEAD:RentalManagement/RentalManagement/Migrations/201611112039042_init too.Designer.cs
<<<<<<< HEAD:RentalManagement/RentalManagement/Migrations/201611112039042_init too.Designer.cs
=======
>>>>>>> 033537337ce6a317496a0607e3d5ec8026ce059a:RentalManagement/RentalManagement/Migrations/201611112143455_reinit.Designer.cs
// <auto-generated />
namespace RentalManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
<<<<<<< HEAD:RentalManagement/RentalManagement/Migrations/201611112039042_init too.Designer.cs
    public sealed partial class inittoo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inittoo));
        
        string IMigrationMetadata.Id
        {
            get { return "201611112039042_init too"; }
=======
    public sealed partial class reinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201611112143455_reinit"; }
>>>>>>> 033537337ce6a317496a0607e3d5ec8026ce059a:RentalManagement/RentalManagement/Migrations/201611112143455_reinit.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
<<<<<<< HEAD:RentalManagement/RentalManagement/Migrations/201611112039042_init too.Designer.cs
=======
// <auto-generated />
namespace RentalManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inittoo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inittoo));
        
        string IMigrationMetadata.Id
        {
            get { return "201611112039042_init too"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> 2cfaf882138d27a8aaed090156bc67e7c6db911f:RentalManagement/RentalManagement/Migrations/201611112039042_init too.Designer.cs
=======
>>>>>>> 033537337ce6a317496a0607e3d5ec8026ce059a:RentalManagement/RentalManagement/Migrations/201611112143455_reinit.Designer.cs
